
BackendTaskDefinition:
  Type: AWS::ECS::TaskDefinition
  Properties:
    Family: BackendTask
    NetworkMode: awsvpc
    RequiresCompatibilities:
      - FARGATE
    Cpu: "256" # default value
    Memory: "512" # default value
    TaskRoleArn: # 實際值將在部署時確定
    ExecutionRoleArn: # 實際值將在部署時確定
    ContainerDefinitions:
      - Name: backend
        Image: 709825985650.dkr.ecr.us-east-1.amazonaws.com/sygna/sygna-hub:latest-beta
        PortMappings:
          - ContainerPort: 8080 # default value
        Environment:
          - Name: CONTAINER_PORT
            Value: "8080" # default value
          - Name: DB_HOST
            Value: # Please change this via your settings
          - Name: DB_NAME
            Value: # Please change this via your settings
          - Name: DB_PASSWORD
            Value: # Please change this via your settings
          - Name: DB_PORT
            Value: "5432"
          - Name: DB_USER
            Value:  # Please change this via your settings
          - Name: DB_DRIVER
            Value: postgres
          - Name: ADMIN_ACCOUNT
            Value: "{mail-account@your-mail-server}" # default value, please change this via your settings
          - Name: ADMIN_PASSWORD
            Value: # 實際值將在部署時確定 Password should contain at least 6 letters, at least 1 number, at least 1 upper case and at least 1 special character
          - Name: ALLOW_ORIGINS
            Value: "[{your-frontend-domain}]" # default value, please change this via your settings
          - Name: PORT
            Value: "8080" # default value
          - Name: CALLBACK_HOST
            Value: "https://{backend-url}" # default value, please change this via your settings
          - Name: COOKIE_DOMAIN
            Value: "https://{backend-url}" # default value, please change this via your settings
          - Name: ACCESS_TOKEN_EXPIRES_IN_SECONDS
            Value: "14400"
          - Name: DATA_ENCRYPTION_KEY
            Value: "00000000000000000000000000000000"   # a new encryption key generated by VASP to encrypt service credential in the database, should be a 32 character long hex string
          - Name: JWT_SECRET
            Value: "wowsuperjwtsecret" #signing key for JWT token, you should keep this value in secret place
          - Name: LICENSE_KEY
            Value: "" # license key = Sygna Hub API key = "Your API Key" (retrieved when Sygna Hub account registration is completed)
          - Name: VASP_CODE
            Value: "" # retrieved when Sygna Hub account registration is completed
          - Name: EMAIL_HOST
            Value: ""  # email address and password of sender
          - Name: EMAIL_ACCOUNT
            Value: "" # please input the AWS IAM user name and password if you want to use AWS SES to send email
          - Name: EMAIL_PASSWORD
            Value: "" # please input the AWS IAM user name and password if you want to use AWS SES to send email
          - Name: EMAIL_DISPLAY_NAME
            Value: "" # name of sender, it would be useless when you enable TLS
          - Name: EMAIL_SUBJECT_PREFIX
            Value: "" # prefix of the mail subject
          - Name: EMAIL_TLS_SUPPORT
            Value: "" # Please enable the below attributes if you want to support TLS (EMAIL_TLS_SUPPORT=TRUE)
          - Name: EMAIL_FROM_EMAIL
            Value: "" # from_email: <the email address of your sender>
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: /ecs/sygna-hub-logs
            awslogs-region: #  (EX：ap-northeast-1)
            awslogs-stream-prefix: backend






